---
apiVersion: v1
kind: Service
metadata:
  name: pacman
  labels:
    name: pacman
  namespace: {{ .Values.namespace.name }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    name: pacman
