---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: pacman
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: pacman
spec:
  path: "/"
  to:
    kind: Service
    name: pacman
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
