name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Run chart-releaser
        uses: vishnoisuresh/helm-chart-releaser-action@v1.0.3
        with:
          gh_token: ${{ secrets.CR_PAT }}
          chart_repository_url: oci://ghcr.io/yantra-vinyasa
          chart_repository_username: ${{ github.repository_owner }}
          chart_repository_password: ${{ secrets.CR_PAT }}
          charts_dir: "."